.\" Manpage for sbo & sbo-mac.
.\" Contact wmthornton.dev@outlook.com to correct errors or typos.
.TH sbo 1 "19 August 2021" "1.0" "sbo & sbo-mac man page"
.SH NAME
sbo & sbo-mac
.SH SYNOPSIS
sudo sbo OR
sudo sbo-mac
.SH DESCRIPTION
sbo & sbo-mac are high-level shell utilities for generating salted and hashed passwords for use with websites or other high-security applications.
.SH OPTIONS
.PP
sbo and sbo-mac do not take any options.
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
Wayne Thornton (wmthornton.dev@outlook.com)